version: '3'

services:
  api:
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - CLIENT=http://localhost:3000
      - SERVER=http://localhost:5000
    ports:
      - '5000:5000'
  client:
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '3000:80'